### ISSUE TITLE
kafka run error!!

### ISSUE THREAD

**Issue by mincloud1501** [mincloud1501/BigData#1]
[Windows에서 kafka 실행 시 run 오류]
> bin/windows/kafka-server-start.bat config/server.properties
> INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistratio
n$)
>ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
  java.lang.NoSuchMethodError: **joptsimple.OptionParser**.<init>(Z)V
        at kafka.Kafka$.getPropsFromArgs(Kafka.scala:33)
        at kafka.Kafka$.main(Kafka.scala:67)
        at kafka.Kafka.main(Kafka.scala)

**Comment by mincloud1501** [comment]
[joptsimple.OptionParser 충돌 해결]
zookeeper run시 설치된 java jre path내의 lib/ext/에 avro (de)Serialize test 용도로 import해 놓은 **avro-tools-1.8.1.jar**와 충돌...
--> 파일 삭제하여 해결...avro-tools-1.8.1.jar project에서는 add library로 해결!!
